name: 'Setup MySQL'
description: 'Setup MySQL database'
author: 'Christian Weinberger'
branding:
  icon: 'database'
inputs:
  version:
    description: 'The MySQL version'
    required: false
    default: 'latest'
  hostName:
    description: 'The hostname'
    required: false
    default: "mysql"
  hostPort:
    description: 'The port of host'
    required: false
    default: 3306
  containerPort:
    description: 'The port of container'
    required: false
    default: 3306
  rootPassword:
    description: 'The root user password'
    required: true
  characterSet:
    description: 'The character set of MySQL server'
    required: false
    default: 'utf8mb4'
  collation:
    description: 'The collation of MySQL server'
    required: false
    default: 'utf8mb4_general_ci'
  sqlMode:
    description: 'The sql modes, fx. NO_ENGINE_SUBSTITUTION'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
