name: Test Github Action
on: [push, pull_request]
jobs:
  mysql57:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      uses: chhsiung/github-actions-mysql@IG-213
      with:
        version: 5.7
        containerPort: 3306
        rootPassword: password
        characterSet: utf8mb4
        collation: utf8mb4_general_ci
        sqlMode: STRICT_ALL_TABLES
    - name: Print running docker containers
      run: docker ps
    - name : Check mysql settings
      run: mysql -h 127.0.0.1 -uroot -ppassword -P 3306 -e "SELECT @@GLOBAL.sql_mode;"
  mysql8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      uses: chhsiung/github-actions-mysql@IG-213
      with:
        version: 8
        containerPort: 3306
        rootPassword: password
    - name: Print running docker containers
      run: docker ps
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'      
    - name: mysql healthcheck
      run: mysqladmin -h 127.0.0.1 ping -uroot -ppassword
    - name: Check mysql settings
      run: mysql -h 127.0.0.1 -uroot -ppassword -P 3306 -e "SELECT @@GLOBAL.sql_mode;"
