name: Test Github Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shutdown existing MySQL
      run: sudo service mysql stop
    - name: Set up MySQL
      uses: cweinberger/github-actions-mysql@master
      with:
        version: 5.7
        hostPort: 33069
        containerPort: 3306
        rootPassword:
        user: TestUser
        password: TestPassword
        database: TestDatabase
        characterSet: utf8mb4
        collation: utf8mb4_general_ci
        sqlMode: NO_ENGINE_SUBSTITUTION
