name: Test Github Action
on: [push, pull_request]
jobs:
  mysql57:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      uses: chhsiung/github-actions-mysql@main
      with:
        version: 5.7
        containerPort: 3306
        rootPassword: password
        characterSet: utf8mb4
        collation: utf8mb4_general_ci
        sqlMode: STRICT_ALL_TABLES
    - name: Print running docker containers
      run: docker ps
    - name: Wait for mysql
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -uroot -ppassword --silent; do
            sleep 1
        done
      shell: bash
    - name: Check mysql settings
      run: mysql -h 127.0.0.1 -uroot -ppassword -P 3306 -e "SELECT @@GLOBAL.sql_mode;"
  mysql8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      uses: chhsiung/github-actions-mysql@main
      with:
        version: 8
        containerPort: 3306
        rootPassword: password
    - name: Print running docker containers
      run: docker ps
    - name: Wait for mysql
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -uroot -ppassword --silent; do
            sleep 1
        done
      shell: bash
    - name: Check mysql settings
      run: mysql -h 127.0.0.1 -uroot -ppassword -P 3306 -e "SELECT @@GLOBAL.sql_mode;"
